### ISSUE TITLE
summary

### ISSUE THREAD

**Issue by darlanmendonca** [knowledge-club/javascript#2]
Think about summary, I suggest anything like this
- ecmascript [en](#), [pt-br](#)
- var [en](#), [pt-br](#)
- let [en](#), [pt-br](#)
- const [en](#), [pt-br](#)
- string [en](#), [pt-br](#)
- number [en](#), [pt-br](#)
- boolean
- array
- object
- operator
- string methods
- number methods
- array methods
- object methods
- conditionals operators
  ...

**Comment by darlanmendonca** [comment]
Or this
- ecmascript [en](#), [pt-br](#)
- var [en](#), [pt-br](#)
- let [en](#), [pt-br](#)
- const [en](#), [pt-br](#)
  ...
- [string methods](#string-methods.summary.md)
- [number methods](#number-methods.summary.md)
- [array methods](#number-methods.summary.md)

and in a sub summary, has a summary complete with names of methods, example of array.summary
- every() [en](#), [pt-br](#)
- filter() [en](#), [pt-br](#)
- forEach() [en](#), [pt-br](#)
- indexOf() [en](#), [pt-br](#)
  ...

or you like more anything like this

**Comment by darlanmendonca** [comment]
@WendellAdriel @khaosdoctor @OdineiRibeiro what you think?

**Comment by khaosdoctor** [comment]
Too many values I believe... It would be better if we had all the links within the same summary, this way we will create too many links to other pages. The table of contents should be simple and small

**Comment by darlanmendonca** [comment]
ok, is a great summary, but, like our contributes specs, only members write in read.md, PR's change only the article files

closing this issue, 

we will use a simple and flat summary in readme.md
